# pages:

_event:
    pattern:  /event/{id}/{slug}.html
    defaults: { _controller: "MyAppUserBundle:Default:event", _format: html }
    requirements:
        id: ^[1-9]\d*$
        slug: ^\w[\w\-]*\w$

# webservices

_email:
    pattern:  /email.json
    defaults: { _controller: "MyAppUserBundle:WebService:email", _format: json }

_participants_list:
    pattern:  /participants-list.json
    defaults: { _controller: "MyAppUserBundle:WebService:participantsList", _format: json }

_create_event_execute:
    pattern:  /create-event.json
    defaults: { _controller: "MyAppUserBundle:WebService:createEvent", _format: json }

##########################################################

#_events_list:
#    pattern:  /{initial}/events-list.json
#    defaults: { _controller: "MyAppUserBundle:WebServices:clientsList", _format: json }
#    requirements:
#        initial: ^[\w\*]$
